site_name: SMS_BP_Docs
repo_url: https://github.com/joemans3/SMS_BP
nav:
  - Home: 
    - 'Hello and Install': index.md
  - User Guide: 
    - 'Starter Guide': User_Guide_MD.md
    - 'sim_config Documentation': sim_config.md
  - About:
    - 'License': license.md

theme: 
  name: material
  palette:
    primary: green
    scheme: slate
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.footer
    - search.suggest
font:
  text: 'Roboto'
  code: 'Roboto Mono'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
