name: pages
on:
  push:
    branches:
      - master 
    paths:
      - 'docs/**'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mkdocs and pymdown-extensions
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions
      - name: Build and deploy
        run: |
          cd docs
          mkdocs build
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.SMS_BP_CI_GH }}
